#!/usr/bin/env python3
"""
compare_asr_curves.py

Combine ASR-per-client CSVs (generated by balance_with_metrics.py)
and plot mean ± std ASR curves per aggregator.

Usage:
  python compare_asr_curves.py --csvs asr_per_client_balance_clients10_atksign_flip.csv \
                               asr_per_client_fedavg_clients10_atksign_flip.csv \
                               asr_per_client_trim_clients10_atksign_flip.csv
  (you can pass any number of CSV files)
"""

import argparse
import csv
import os
import numpy as np
import matplotlib.pyplot as plt

def load_asr_csv(csv_path):
    """Load per-client ASR CSV into numpy array [num_rounds x num_clients]."""
    rounds = []
    asr_matrix = []
    with open(csv_path, "r") as f:
        reader = csv.reader(f)
        header = next(reader)
        clients = header[1:]  # skip 'round'
        for row in reader:
            rounds.append(int(row[0]))
            asr_matrix.append([float(x) for x in row[1:]])
    return np.array(rounds), np.array(asr_matrix), clients

def extract_label(csv_path):
    """Infer aggregator label from filename."""
    fname = os.path.basename(csv_path)
    parts = fname.split("_")
    # example: asr_per_client_balance_clients10_atksign_flip.csv
    for p in ["balance", "fedavg", "trim", "median", "krum"]:
        if p in fname:
            return p
    return fname.split(".")[0]

def plot_comparison(csv_paths, out_dir="plots"):
    os.makedirs(out_dir, exist_ok=True)
    plt.figure(figsize=(8,5))

    for csv_file in csv_paths:
        rounds, asr_matrix, clients = load_asr_csv(csv_file)
        mean_asr = np.mean(asr_matrix, axis=1)
        std_asr = np.std(asr_matrix, axis=1)
        label = extract_label(csv_file)
        plt.plot(rounds, mean_asr, label=label)
        plt.fill_between(rounds, mean_asr-std_asr, mean_asr+std_asr, alpha=0.2)

    plt.xlabel("Round")
    plt.ylabel("Attack Success Rate (mean ± std over benign clients)")
    plt.title("ASR Comparison Across Aggregators")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    out_path = os.path.join(out_dir, "asr_comparison.png")
    plt.savefig(out_path)
    plt.close()
    print("Saved comparison plot to", out_path)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--csvs", nargs="+", required=True, help="list of ASR per-client CSV files to compare")
    parser.add_argument("--out", default="plots", help="output directory")
    args = parser.parse_args()
    plot_comparison(args.csvs, args.out)
